---
# tasks file for Ansible_Apache
#
- name:     install_package
  become:   true 
  package:  
    name    = {{ package_name }} 
    state   = latest     

- name:     enable_service
  become:   yes
  service:  
    name    = {{ service_name }}
    state   = started
    enabled = true
